const KEY="cycleObserver.records.v2", OLD="cycleObserver.records.v1", PINKEY="cycleObserver.pin.v1";
let records=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD)||"{}");
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const iso=d=>{let x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}, today=()=>iso(new Date());
async function hash(s){let b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode("cycle-observer|"+s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function persist(){localStorage.setItem(KEY,JSON.stringify(records));renderAll()}
function select(g,v){document.querySelectorAll(`#${g} button`).forEach(b=>b.classList.toggle("selected",b.dataset.value===v))}
function selected(g){return document.querySelector(`#${g} button.selected`)?.dataset.value||""}
["bleeding","sensation"].forEach(g=>document.querySelectorAll(`#${g} button`).forEach(b=>b.onclick=()=>select(g,b.dataset.value)));
function loadDate(d){$("#date").value=d;let r=records[d]||{};select("bleeding",r.bleeding||"");select("sensation",r.sensation||"");["appearance","stretch","frequency","code","meds","notes"].forEach(k=>$("#"+k).value=r[k]||"");$("#intercourse").checked=!!r.intercourse;$("#peak").checked=!!r.peak}
function show(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id));renderAll()}
$$("nav button").forEach(b=>b.onclick=()=>show(b.dataset.view));$("#todayBtn").onclick=$("#quickEntry").onclick=()=>{show("entry");loadDate(today())};$("#date").onchange=e=>loadDate(e.target.value);
$("#saveBtn").onclick=()=>{let d=$("#date").value;if(!d)return alert("Escolha uma data.");records[d]={bleeding:selected("bleeding"),sensation:selected("sensation"),appearance:$("#appearance").value,stretch:$("#stretch").value,frequency:$("#frequency").value,code:$("#code").value.trim(),intercourse:$("#intercourse").checked,peak:$("#peak").checked,meds:$("#meds").value.trim(),notes:$("#notes").value.trim()};persist();show("home")};
$("#deleteBtn").onclick=()=>{let d=$("#date").value;if(records[d]&&confirm("Excluir este registro?")){delete records[d];persist();loadDate(d)}};

function cycleStarts(){let ds=Object.keys(records).sort(),out=[],prev=false;for(let d of ds){let b=!!records[d].bleeding;if(b&&!prev)out.push(d);prev=b}return out}
function diff(a,b){return Math.floor((new Date(b+"T12:00")-new Date(a+"T12:00"))/86400000)}
function renderHome(){let ds=Object.keys(records).sort(), starts=cycleStarts(), lastStart=starts.at(-1), last=ds.at(-1), peaks=ds.filter(d=>records[d].peak), lp=lastStart?peaks.filter(d=>d>=lastStart).at(-1):peaks.at(-1);$("#cycleDay").textContent=lastStart?Math.max(1,diff(lastStart,today())+1):"—";$("#homeStart").textContent=lastStart||"—";$("#homeLast").textContent=last||"—";$("#homePeak").textContent=lp||"—";$("#statCycles").textContent=starts.length;$("#statRecords").textContent=ds.length;$("#statLength").textContent=starts.length>1?diff(starts.at(-2),starts.at(-1))+" dias":"—";let recent=ds.slice(-5).reverse();$("#recentDays").innerHTML=recent.length?recent.map(d=>`<div class="recent" data-date="${d}"><div><b>${d}</b><small>${[records[d].bleeding,records[d].sensation,records[d].code].filter(Boolean).join(" • ")||"registro"}</small></div><span>${records[d].peak?"Peak ":""}${records[d].intercourse?"♥":""}</span></div>`).join(""):"<p class='sub'>Comece registrando o dia de hoje.</p>";$$(".recent").forEach(x=>x.onclick=()=>{show("entry");loadDate(x.dataset.date)})}
function stamp(r){if(r?.peak)return"yellow";if(r?.bleeding)return"red";if(r?.sensation==="seca")return"green";return r&&(r.code||r.appearance||r.sensation)?"white":""}
function renderChart(){let start=$("#cycleStart").value||cycleStarts().at(-1)||Object.keys(records).sort()[0]||today();$("#cycleStart").value=start;let base=new Date(start+"T12:00"),h="";for(let i=0;i<35;i++){let x=new Date(base);x.setDate(base.getDate()+i);let d=iso(x),r=records[d],s=stamp(r);h+=`<div class="day" data-date="${d}"><div class="n">${i+1}</div><div class="date">${d.slice(5)}</div><div class="stamp ${s}"></div><div class="code">${r?.code||r?.bleeding||""}${r?.peak?" • P":""}${r?.intercourse?" • ♥":""}</div></div>`}$("#chartGrid").innerHTML=h;$$(".day").forEach(x=>x.onclick=()=>{show("entry");loadDate(x.dataset.date)})}$("#cycleStart").onchange=renderChart;
function renderHistory(){let q=($("#historySearch").value||"").toLowerCase(),ds=Object.keys(records).sort().reverse().filter(d=>(d+" "+JSON.stringify(records[d])).toLowerCase().includes(q));$("#historyList").innerHTML=ds.length?ds.map(d=>`<div class="hist" data-date="${d}"><div><b>${d}</b><small>${[records[d].bleeding,records[d].sensation,records[d].code].filter(Boolean).join(" • ")||"registro"}</small></div><span>${records[d].peak?"Peak ":""}${records[d].intercourse?"♥":""}</span></div>`).join(""):"<p class='sub'>Nenhum registro encontrado.</p>";$$(".hist").forEach(x=>x.onclick=()=>{show("entry");loadDate(x.dataset.date)})}$("#historySearch").oninput=renderHistory;
function renderAll(){renderHome();renderChart();renderHistory();let on=!!localStorage.getItem(PINKEY);$("#pinOff").classList.toggle("hidden",on);$("#pinOn").classList.toggle("hidden",!on)}
function download(n,t,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("#exportJson").onclick=()=>download("cycle-observer-backup.json",JSON.stringify({app:"Cycle Observer",version:2,exported:new Date().toISOString(),records},null,2),"application/json");
$("#exportCsv").onclick=()=>{let hs=["date","bleeding","sensation","appearance","stretch","frequency","code","intercourse","peak","meds","notes"],esc=v=>`"${String(v??"").replaceAll('"','""')}"`,rows=Object.keys(records).sort().map(d=>hs.map(h=>esc(h==="date"?d:records[d][h])).join(","));download("cycle-observer.csv",[hs.join(","),...rows].join("\n"),"text/csv")};
$("#importJson").onchange=async e=>{try{let o=JSON.parse(await e.target.files[0].text());if(!o.records)throw 0;if(confirm("Substituir os dados atuais pelo backup?")){records=o.records;persist();$("#importReport").textContent="Backup restaurado."}}catch{alert("Arquivo inválido.")}};
function parseCSV(t){let rows=[],row=[],c="",q=false;for(let i=0;i<t.length;i++){let x=t[i];if(x=='"'&&q&&t[i+1]=='"'){c+='"';i++}else if(x=='"')q=!q;else if(x==","&&!q){row.push(c);c=""}else if((x=="\n"||x=="\r")&&!q){if(x=="\r"&&t[i+1]=="\n")i++;row.push(c);if(row.some(y=>y.trim()))rows.push(row);row=[];c=""}else c+=x}row.push(c);if(row.some(y=>y.trim()))rows.push(row);return rows}
$("#importMaya").onchange=async e=>{let rows=parseCSV(await e.target.files[0].text());if(rows.length<2)return alert("CSV vazio.");let hs=rows[0].map(x=>x.trim().toLowerCase()),di=hs.findIndex(h=>/date|data|day/.test(h)),pi=hs.findIndex(h=>/period|menstr|bleed|flow/.test(h));if(di<0){$("#importReport").textContent="Não encontrei coluna de data. Nenhum dado foi alterado.";return}let a=0,b=0;for(let r of rows.slice(1)){let raw=(r[di]||"").trim(),d=null,m=raw.match(/^(\d{4})[-\/](\d{1,2})[-\/](\d{1,2})/);if(m)d=`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`;else{let x=new Date(raw);if(!isNaN(x))d=iso(new Date(x.getFullYear(),x.getMonth(),x.getDate(),12))}if(!d)continue;let ex=records[d]||{},v=pi>=0?(r[pi]||"").trim():"",has=/yes|true|period|menstr|light|medium|heavy|spot|1/i.test(v);records[d]={...ex};if(has&&!ex.bleeding){records[d].bleeding=/heavy/i.test(v)?"H":/medium/i.test(v)?"M":/light/i.test(v)?"L":"VL";b++}records[d].notes=[ex.notes,`Importado do Maya${v?": "+v:""}`].filter(Boolean).join(" | ");a++}persist();$("#importReport").textContent=`Importação: ${a} linhas reconhecidas; ${b} registros de sangramento identificados. Revise os dados. Nenhuma observação do método foi inferida retrospectivamente.`};
$("#clearAll").onclick=()=>{if(confirm("Apagar TODOS os registros locais? Faça backup antes.")){records={};persist();loadDate(today())}};
$("#setPin").onclick=async()=>{let a=$("#newPin").value,b=$("#newPin2").value;if(!/^\d{4,12}$/.test(a))return alert("Use um PIN de 4 a 12 dígitos.");if(a!==b)return alert("Os PINs não coincidem.");localStorage.setItem(PINKEY,await hash(a));$("#newPin").value=$("#newPin2").value="";renderAll();alert("PIN ativado.")};
$("#removePin").onclick=()=>{if(confirm("Remover o bloqueio por PIN?")){localStorage.removeItem(PINKEY);renderAll()}};
function lock(){if(localStorage.getItem(PINKEY)){$("#unlockPin").value="";$("#lockMsg").textContent="";$("#lockScreen").classList.remove("hidden");setTimeout(()=>$("#unlockPin").focus(),50)}}$("#lockBtn").onclick=lock;
$("#unlockBtn").onclick=async()=>{if(await hash($("#unlockPin").value)===localStorage.getItem(PINKEY))$("#lockScreen").classList.add("hidden");else $("#lockMsg").textContent="PIN incorreto."};$("#unlockPin").onkeydown=e=>{if(e.key==="Enter")$("#unlockBtn").click()};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
localStorage.setItem(KEY,JSON.stringify(records));loadDate(today());$("#cycleStart").value=cycleStarts().at(-1)||Object.keys(records).sort()[0]||today();renderAll();if(localStorage.getItem(PINKEY))lock();